### ISSUE TITLE
restart button not working

### ISSUE THREAD

**Issue by alexandrecuer** [emoncms/config#23]
Dont know if others are facing the same issue but I have troubles with the restart button of the config module

I had to do the following

# config_controller.php

change line 29 from
```$restart_log= sprintf("%s/%s",$homedir,$config->restart_log_name);```
to 
```$restart_log= $config->restart_log_name;```

# config_module.php
lines 16 to 18 are 
```
    public $config_file = "/etc/emonhub/emonhub.conf";
    public $logfile = "/var/log/emonhub/emonhub.log";
    public $restart_log_name = "restart.log";
```
change line 18 into
```public $restart_log_name = "/var/log/emonhub/restart.log";```

and at last create the log file manually

```
cd /var/log/emonhub
sudo touch restart.log
sudo chown pi:pi restart.log
```

@TrystanLea : which is the best place for the file creation ? in the install.sh of emonhub, in the EmonScripts ?

Alex

**Comment by TrystanLea** [comment]
Thanks @alexandrecuer placing the restart.log in /var/log/emoncms/emonhub-restart.log works ok as this directory already has the same permissions as service-runner (e.g pi user)
The following seems to be working ok here:
https://github.com/emoncms/config/commit/26d41e027a3b54c6dc51b38e9e840bca3947e6f0

**Comment by alexandrecuer** [comment]
OK thanks it is working
It was not working initially as I forgot to switch on branch master
